<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula [
<!ELEMENT matricula (ciclo,alumnos)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT alumnos (alumno)+>
<!ELEMENT alumno (nombre,year,asignaturas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT asignaturas (asignatura)+>
<!ELEMENT asignatura (#PCDATA)>
]>

<matricula>
    <ciclo>DAM</ciclo>
    <alumnos>
        <alumno>
            <nombre>David</nombre>
            <year>2023</year>
            <asignaturas>
                <asignatura>M04</asignatura>
            </asignaturas>
        </alumno>
    </alumnos>
</matricula>